import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const fkDisplayFont = localFont({
  src: [{
    path: './_shared/assets/fonts/fk-display/FKDisplay-RegularAlt.woff2',
    weight: '300'
  },
  ],
  variable: '--font-fk-display-alt',
});

const suisseFont = localFont({
  src: [
    {
      path: './_shared/assets/fonts/suisse-intl/SuisseIntl-Black.woff2',
      weight: '900'
    },
    {
      path: './_shared/assets/fonts/suisse-intl/SuisseIntl-Bold.woff2',
      weight: '700'
    },
    {
      path: './_shared/assets/fonts/suisse-intl/SuisseIntl-Light.woff2',
      weight: '200'
    },
    {
      path: './_shared/assets/fonts/suisse-intl/SuisseIntl-Medium.woff2',
      weight: '500'
    },
    {
      path: './_shared/assets/fonts/suisse-intl/SuisseIntl-Regular.woff2',
      weight: '400'
    },
    {
      path: './_shared/assets/fonts/suisse-intl/SuisseIntl-Semibold.woff2',
      weight: '600'
    },
    {
      path: './_shared/assets/fonts/suisse-intl/SuisseIntl-Thin.woff2',
      weight: '100'
    },
  ],
  variable: "--font-suisse-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fkDisplayFont.variable} ${suisseFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
